### ISSUE TITLE
Incorrect param name

### ISSUE THREAD

**Issue by michaelwheeler** [pfgray/mock-lti2-consumer#4]
The resource link title is being passed as `resource_title`. I think it should be `resource_link_title`.

**Comment by pfgray** [comment]
You're right! looks like [this](https://github.com/pfgray/mock-lti2-consumer/blob/master/src/main/webapp/WEB-INF/assets/scripts/ltiLaunches/lti-launches.html#L74) needs to be updated.

Thanks for the bug report!

**Comment by michaelwheeler** [comment]
No problem. Thanks for a really handy Docker image!

**Comment by pfgray** [comment]
@michaelwheeler, you can grab the fixed version by pulling the latest docker image:

```
docker pull pfgray/mock-lti2-consumer
``` 
thanks again!

**Comment by michaelwheeler** [comment]
Works great! Love this tool for LTI development.
